// Seed festival data for Odisha 2026 — populated by AI agent in production
export interface Festival {
  id: string;
  date: string;           // YYYY-MM-DD
  name_or: string;
  name_en: string;
  odia_day: number;
  odia_month: string;
  odia_year: number;
  tithi?: string;
  significance_or: string;
  significance_en: string;
  traditions_or: string[];
  traditions_en: string[];
  is_bank_holiday: boolean;
  is_govt_holiday: boolean;
  is_odisha_specific: boolean;
  emoji: string;
  location?: string;
}

export const FESTIVALS_2026: Festival[] = [
  {
    id: 'ram-navami-2026',
    date: '2026-04-05',
    name_or: 'ରାମ ନବମୀ',
    name_en: 'Ram Navami',
    odia_day: 22, odia_month: 'ଚୈତ୍ର', odia_year: 1948,
    tithi: 'ଚୈତ୍ର ଶୁକ୍ଳ ନବମୀ',
    significance_or: 'ଭଗବାନ ଶ୍ରୀ ରାମଙ୍କ ଜନ୍ମ ଦିବସ। ଏହି ଦିନ ରାମ ମନ୍ଦିରରେ ବିଶେଷ ପୂଜା ଅର୍ଚ୍ଚନା ହୁଏ। ଭକ୍ତମାନେ ଉପବାସ ରଖି ରାମ ନାମ ଜପ କରନ୍ତି।',
    significance_en: 'Birthday of Lord Rama. Special prayers are held at Ram temples. Devotees fast and chant Ram Naam.',
    traditions_or: ['ଉପବାସ ରଖିବା', 'ରାମ ନାମ ଜପ', 'ସୁନ୍ଦରକାଣ୍ଡ ପାଠ', 'ମନ୍ଦିରରେ ଦର୍ଶନ'],
    traditions_en: ['Fasting', 'Ram Naam chanting', 'Sundarkand recitation', 'Temple visit'],
    is_bank_holiday: false, is_govt_holiday: false, is_odisha_specific: false,
    emoji: '🙏',
  },
  {
    id: 'pana-sankranti-2026',
    date: '2026-04-14',
    name_or: 'ପଣା ସଂକ୍ରାନ୍ତି',
    name_en: 'Pana Sankranti',
    odia_day: 1, odia_month: 'ବୈଶାଖ', odia_year: 1948,
    tithi: 'ମେଷ ସଂକ୍ରାନ୍ତି',
    significance_or: 'ଏହା ଓଡ଼ିଆ ନୂଆ ବର୍ଷ। ଏହି ଦିନ ପଣା (ବେଲ ଫଳ, କଞ୍ଚା ଆମ୍ବ, ଛେନା ଓ ଗୁଡ଼ ଦ୍ୱାରା ପ୍ରସ୍ତୁତ ବିଶେଷ ପାନୀୟ) ଜଗନ୍ନାଥଙ୍କୁ ଅର୍ପଣ କରାଯାଏ। ଘରେ ଘରେ ପଣା ତିଆରି ହୋଇ ବିତରଣ ହୁଏ।',
    significance_en: 'Odia New Year. Pana (a special drink made from bael fruit, raw mango, cottage cheese, and jaggery) is offered to Lord Jagannath and distributed to all.',
    traditions_or: ['ପଣା ପ୍ରସ୍ତୁତି ଓ ବିତରଣ', 'ଜଗନ୍ନାଥ ମନ୍ଦିରରେ ପୂଜା', 'ଘର ସଫା ଓ ରଙ୍ଗୋଳି', 'ନୂଆ ବର୍ଷ ଶୁଭେଚ୍ଛା', 'ଶୀତଳ ଷଷ୍ଠୀ'],
    traditions_en: ['Pana preparation & sharing', 'Jagannath temple puja', 'House cleaning & rangoli', 'New Year wishes', 'Sheetala Shasthi'],
    is_bank_holiday: true, is_govt_holiday: true, is_odisha_specific: true,
    emoji: '🎊', location: 'Odisha',
  },
  {
    id: 'ambedkar-jayanti-2026',
    date: '2026-04-14',
    name_or: 'ଡ଼ଃ ଆମ୍ବେଦକର ଜୟନ୍ତୀ',
    name_en: 'Dr. Ambedkar Jayanti',
    odia_day: 1, odia_month: 'ବୈଶାଖ', odia_year: 1948,
    significance_or: 'ଭାରତ ରତ୍ନ ଡ଼ଃ ଭୀମରାଓ ରାମଜୀ ଆମ୍ବେଦକରଙ୍କ ଜନ୍ମ ଦିବସ। ସେ ଭାରତୀୟ ସମ୍ବିଧାନର ଶ୍ରୀ-ଶ୍ରୀ ନିର୍ମାତା।',
    significance_en: 'Birth anniversary of Bharat Ratna Dr. B.R. Ambedkar, the principal architect of the Indian Constitution.',
    traditions_or: ['ଶ୍ରଦ୍ଧାଞ୍ଜଳି ଅର୍ପଣ', 'ସ୍ମୃତି ସଭା', 'ସାମାଜିକ ସଚେତନତା ର‌ୟାଲି'],
    traditions_en: ['Tributes', 'Memorial gatherings', 'Social awareness rallies'],
    is_bank_holiday: true, is_govt_holiday: true, is_odisha_specific: false,
    emoji: '🇮🇳',
  },
  {
    id: 'good-friday-2026',
    date: '2026-04-03',
    name_or: 'ଗୁଡ଼ ଫ୍ରାଇଡ଼େ',
    name_en: 'Good Friday',
    odia_day: 20, odia_month: 'ଚୈତ୍ର', odia_year: 1948,
    significance_or: 'ଯୀଶୁ ଖ୍ରୀଷ୍ଟଙ୍କ ଶ୍ରେୟ ଅର୍ଥେ ସ୍ତ୍ୱ ସ୍ମୃତିରେ ଖ୍ରୀଷ୍ଟ ଧର୍ମାବଲମ୍ବୀ ମାନଙ୍କ ଦ୍ୱାରା ପାଳିତ ଦିବସ।',
    significance_en: 'Commemorates the crucifixion of Jesus Christ. Observed by Christians worldwide with prayer and fasting.',
    traditions_or: ['ଗିର୍ଜାଘରରେ ପ୍ରାର୍ଥନା', 'ଉପବାସ', 'ଖ୍ୟ ଶ୍ୟ ପ ଚ ଳ'],
    traditions_en: ['Church prayers', 'Fasting', 'Processions'],
    is_bank_holiday: true, is_govt_holiday: false, is_odisha_specific: false,
    emoji: '✝️',
  },
  {
    id: 'rath-yatra-2026',
    date: '2026-06-20',
    name_or: 'ରଥ ଯାତ୍ରା',
    name_en: 'Rath Yatra',
    odia_day: 6, odia_month: 'ଆଷାଢ଼', odia_year: 1948,
    tithi: 'ଆଷାଢ଼ ଶୁକ୍ଳ ଦ୍ୱିତୀୟା',
    significance_or: 'ଶ୍ରୀ ଜଗନ୍ନାଥ, ବଳଭଦ୍ର ଓ ସୁଭଦ୍ରାଙ୍କ ରଥ ଯାତ୍ରା ପୁରୀ ଧାମରେ ଅନୁଷ୍ଠିତ ହୁଏ। ଏହା ବିଶ୍ୱର ସବୁଠାରୁ ବଡ଼ ରଥ ଉତ୍ସବ। ଲକ୍ଷ ଲକ୍ଷ ଭକ୍ତ ପୁରୀ ଆସନ୍ତି।',
    significance_en: 'The grand chariot festival of Lord Jagannath, Balabhadra & Subhadra at Puri — the world\'s largest chariot festival. Millions of devotees gather.',
    traditions_or: ['ରଥ ଟଣା', 'ଛେରା ପହଁରା (ରାଜା ଝାଡ଼ ଦିଅନ୍ତି)', 'ପୋଡ଼ପିଠା ଖାଇବା', '୯ ଦିନ ଧରି ଉତ୍ସବ', 'ଗୁଣ୍ଡିଚା ଯାତ୍ରା'],
    traditions_en: ['Chariot pulling', 'Chhera Pahanra (king sweeps)', 'Poda Pitha sweets', '9-day celebration', 'Gundicha Yatra'],
    is_bank_holiday: true, is_govt_holiday: true, is_odisha_specific: true,
    emoji: '🛕', location: 'Puri, Odisha',
  },
  {
    id: 'nuakhai-2026',
    date: '2026-09-01',
    name_or: 'ନୁଆଖାଇ',
    name_en: 'Nuakhai',
    odia_day: 10, odia_month: 'ଭାଦ୍ରବ', odia_year: 1948,
    tithi: 'ଭାଦ୍ର ଶୁକ୍ଳ ପଞ୍ଚମୀ',
    significance_or: 'ଏହା ପଶ୍ଚିମ ଓଡ଼ିଶାର ସବୁଠାରୁ ବଡ଼ ଫସଲ ଉତ୍ସବ। ନୂଆ ଚାଉଳ ଦେବୀ ଶ୍ରୀ ଶ୍ରୀ ସମ୍ବଲ ପୁରୀ ଠାକୁରାଣୀଙ୍କ ଉଦ୍ଦେଶ୍ୟରେ ଅର୍ପଣ ପରେ ଘରର ବଡ଼ ଛୋଟ ସମସ୍ତ ଏକ ସାଥେ ଖାଆନ୍ତି।',
    significance_en: 'The biggest harvest festival of Western Odisha. New rice is first offered to the deity, then the entire family eats together.',
    traditions_or: ['ନୂଆ ଚାଉଳ ଅର୍ପଣ', 'ପ୍ରସାଦ ଖାଇବା', 'ଜୁହାର ଗ୍ରହଣ', 'ଘର ସଜ୍ଜା', 'ଲୋକ ନୃତ୍ୟ ଓ ଗୀତ'],
    traditions_en: ['Offering new rice', 'Eating prasad', 'Blessing exchange', 'Home decoration', 'Folk dance & songs'],
    is_bank_holiday: false, is_govt_holiday: true, is_odisha_specific: true,
    emoji: '🌾', location: 'Western Odisha',
  },
  {
    id: 'durga-puja-2026',
    date: '2026-10-02',
    name_or: 'ଦୁର୍ଗା ପୂଜା',
    name_en: 'Durga Puja',
    odia_day: 10, odia_month: 'ଆଶ୍ୱିନ', odia_year: 1948,
    tithi: 'ଆଶ୍ୱିନ ଶୁକ୍ଳ ଦଶମୀ',
    significance_or: 'ମା ଦୁର୍ଗାଙ୍କ ବିଜୟ ଉତ୍ସବ। ଦଶ ଦିନ ଧରି ପୂଜା ଅନୁଷ୍ଠିତ ହୁଏ। ବିଜୟ ଦଶମୀ ଦିନ ପ୍ରତିମା ବିସର୍ଜନ।',
    significance_en: 'Victory festival of Goddess Durga. 10-day celebration culminating in idol immersion on Vijayadashami.',
    traditions_or: ['ଦୁର୍ଗା ପ୍ରତିମା ପୂଜା', 'ଆଳ ଅଷ୍ଟମୀ', 'ମହାନବମୀ', 'ଧୁନୁଚି ନୃତ୍ୟ', 'ବିଜୟ ଦଶମୀ ଶୋଭାଯାତ୍ରା'],
    traditions_en: ['Durga idol worship', 'Mahasaptami', 'Mahanavami', 'Dhunuchi dance', 'Vijayadashami procession'],
    is_bank_holiday: true, is_govt_holiday: true, is_odisha_specific: false,
    emoji: '🪔',
  },
  {
    id: 'kartika-purnima-2026',
    date: '2026-11-05',
    name_or: 'କାର୍ତ୍ତିକ ପୂର୍ଣ୍ଣିମା / ବୋଇତ ବନ୍ଦାଣ',
    name_en: 'Kartika Purnima / Boita Bandana',
    odia_day: 15, odia_month: 'କାର୍ତ୍ତିକ', odia_year: 1948,
    tithi: 'କାର୍ତ୍ତିକ ଶୁକ୍ଳ ପୂର୍ଣ୍ଣିମା',
    significance_or: 'ପ୍ରାଚୀନ ଓଡ଼ିଆ ବଣିଜ ଯୁଗକୁ ସ୍ମରଣ କରି ନଦୀ, ପୋଖରୀ ଓ ସମୁଦ୍ରରେ ଛୋଟ ଛୋଟ ଗଡ଼ ଭସାଯାଏ। ଏହି ଦିନ ଓଡ଼ିଶା ସ୍ୱ-ରଚ ନ ଛ ଟ ସ-ଗ-ର ସ ା-ଥ ରୁ-ବ ା-ଣ-ି ଜ-ର-ୋ ।',
    significance_en: 'Celebrates the seafaring heritage of Odisha. Small paper boats (boitas) are floated on rivers, ponds and the sea at dawn to remember ancient maritime traders.',
    traditions_or: ['ଭୋରରେ ନଦୀ ଯାଇ ଗଡ଼ ଭସେଇବା', 'ପ୍ରଦୀପ ଜ୍ୱାଳାଇ ପୂଜା', 'ଆ ଆ ଭାସ ଭ...ଗୀତ ଗାଇବା', 'ସ୍ନାନ ଓ ଦୀପ ଦାନ'],
    traditions_en: ['Floating paper boats at dawn', 'Lamp lighting', 'Singing Boita songs', 'Holy bath & lamp donation'],
    is_bank_holiday: false, is_govt_holiday: false, is_odisha_specific: true,
    emoji: '🪔', location: 'Rivers & coastal areas of Odisha',
  },
  {
    id: 'diwali-2026',
    date: '2026-10-20',
    name_or: 'ଦୀପାବଳୀ / ଦୀପ ଉତ୍ସବ',
    name_en: 'Diwali',
    odia_day: 28, odia_month: 'ଆଶ୍ୱିନ', odia_year: 1948,
    tithi: 'ଆଶ୍ୱିନ ଅମାବାସ୍ୟା',
    significance_or: 'ଆଲୋକର ଉତ୍ସବ। ଘରେ ଘରେ ମାଟି ଦୀପ ଜ୍ୱଳାଯାଏ। ଲକ୍ଷ୍ମୀ ଓ ଗଣେଶ ପୂଜା ହୁଏ।',
    significance_en: 'Festival of Lights. Clay lamps are lit in every home. Lakshmi and Ganesha are worshipped for prosperity.',
    traditions_or: ['ଦୀପ ସଜ୍ଜା', 'ଲକ୍ଷ୍ମୀ ପୂଜା', 'ଆତସ ବାଜି', 'ମିଠା ବିତରଣ', 'ଘର ସଫା'],
    traditions_en: ['Lamp decoration', 'Lakshmi puja', 'Fireworks', 'Sweet distribution', 'House cleaning'],
    is_bank_holiday: true, is_govt_holiday: true, is_odisha_specific: false,
    emoji: '✨',
  },
  {
    id: 'prathamashtami-2026',
    date: '2026-11-25',
    name_or: 'ପ୍ରଥମାଷ୍ଟମୀ',
    name_en: 'Prathamashtami',
    odia_day: 6, odia_month: 'ମାର୍ଗଶିର', odia_year: 1948,
    tithi: 'ମାର୍ଗଶିର ଶୁକ୍ଳ ଅଷ୍ଟମୀ',
    significance_or: 'ଓଡ଼ିଶାର ବିଶୁ ଭ ଅଦ ୍ ୱ ିତ ୀ ୟ ଉ ତ ୍ ସ ବ — ଘ ରର ବ ଡ ଛ ୁ ଆ ର ଦ ୀ ର ।',
    significance_en: 'A unique Odisha festival that celebrates the first-born child of every family with special rituals and sweets.',
    traditions_or: ['ବ ଡ ଛ ୁ ଆ ର ପ ୂ ଜ ା', 'ଏ ‌ ଣ ି ‌ ର ‌ ‍ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌'],
    traditions_en: ['Worship of first-born', 'Enduri pitha', 'Special offerings'],
    is_bank_holiday: false, is_govt_holiday: false, is_odisha_specific: true,
    emoji: '👶',
  },
  {
    id: 'makar-sankranti-2026',
    date: '2026-01-14',
    name_or: 'ମକର ସଂକ୍ରାନ୍ତି',
    name_en: 'Makar Sankranti',
    odia_day: 30, odia_month: 'ପୌଷ', odia_year: 1947,
    significance_or: 'ସୂର୍ଯ୍ୟ ମକର ରାଶିରେ ପ୍ରବେଶ କରନ୍ତି। ଓଡ଼ିଶାରେ ଏହି ଦିନ ଖଡ଼ ଖଡ଼ ଉପାଦ ଭ ବ।',
    significance_en: 'The sun enters Capricorn (Makara). In Odisha, special rice cakes and sesame sweets are prepared.',
    traditions_or: ['ଚୁଙ୍ଗୁଡ଼ି ପିଠା', 'ତିଳ ଲଡ଼ୁ', 'ଉତ୍ତରାୟଣ ପୂଜା', 'ନଦୀ ସ୍ନାନ'],
    traditions_en: ['Chungudi pitha', 'Til ladoo', 'Uttarayan puja', 'River bath'],
    is_bank_holiday: false, is_govt_holiday: false, is_odisha_specific: false,
    emoji: '🌞',
  },
];

export const HOLIDAYS_2026 = [
  { id: 'h1',  date: '2026-01-14', name_or: 'ମକର ସଂକ୍ରାନ୍ତି',         name_en: 'Makar Sankranti',      type: 'govt' as const, is_odisha: true },
  { id: 'h2',  date: '2026-01-26', name_or: 'ଗଣତନ୍ତ୍ର ଦିବସ',           name_en: 'Republic Day',         type: 'both' as const, is_odisha: false },
  { id: 'h16', date: '2026-02-17', name_or: 'ମହା ଶିବ ରାତ୍ରି',           name_en: 'Maha Shivaratri',      type: 'both' as const, is_odisha: false },
  { id: 'h17', date: '2026-03-04', name_or: 'ଇଦ ଉଲ ଫ଼ିତ୍ର (ଈଦ)',         name_en: 'Id-ul-Fitr (Eid)',     type: 'both' as const, is_odisha: false },
  { id: 'h18', date: '2026-03-14', name_or: 'ହୋଲି',                     name_en: 'Holi',                 type: 'bank' as const, is_odisha: false },
  { id: 'h3',  date: '2026-04-03', name_or: 'ଗୁଡ଼ ଫ୍ରାଇଡ଼େ',             name_en: 'Good Friday',          type: 'bank' as const, is_odisha: false },
  { id: 'h4',  date: '2026-04-14', name_or: 'ଡ଼ଃ ଆମ୍ବେଦକର ଜୟନ୍ତୀ',     name_en: 'Dr. Ambedkar Jayanti', type: 'both' as const, is_odisha: false },
  { id: 'h5',  date: '2026-04-14', name_or: 'ପଣା ସଂକ୍ରାନ୍ତି',           name_en: 'Pana Sankranti',       type: 'govt' as const, is_odisha: true },
  { id: 'h6',  date: '2026-05-01', name_or: 'ମେ ଦିବସ',                  name_en: 'May Day',              type: 'both' as const, is_odisha: false },
  { id: 'h7',  date: '2026-05-26', name_or: 'ବୁଦ୍ଧ ପୂର୍ଣ୍ଣିମା',          name_en: 'Buddha Purnima',       type: 'both' as const, is_odisha: false },
  { id: 'h19', date: '2026-05-11', name_or: 'ଇଦ ଉଲ ଜୁହା (ବକ୍ର ଈଦ)',     name_en: 'Id-ul-Zuha (Bakri Eid)', type: 'both' as const, is_odisha: false },
  { id: 'h8',  date: '2026-06-20', name_or: 'ରଥ ଯାତ୍ରା',                name_en: 'Rath Yatra',           type: 'both' as const, is_odisha: true },
  { id: 'h20', date: '2026-07-09', name_or: 'ମହରମ',                     name_en: 'Muharram',             type: 'bank' as const, is_odisha: false },
  { id: 'h9',  date: '2026-08-15', name_or: 'ସ୍ୱାଧୀନତା ଦିବସ',            name_en: 'Independence Day',     type: 'both' as const, is_odisha: false },
  { id: 'h10', date: '2026-09-01', name_or: 'ନୁଆଖାଇ',                   name_en: 'Nuakhai',              type: 'govt' as const, is_odisha: true },
  { id: 'h21', date: '2026-09-04', name_or: 'ଗଣେଶ ଚତୁର୍ଥୀ',             name_en: 'Ganesh Chaturthi',     type: 'govt' as const, is_odisha: false },
  { id: 'h22', date: '2026-09-14', name_or: 'ମିଲାଦ-ଉନ-ନବୀ',             name_en: 'Milad-un-Nabi',        type: 'bank' as const, is_odisha: false },
  { id: 'h11', date: '2026-10-02', name_or: 'ଗାନ୍ଧି ଜୟନ୍ତୀ',             name_en: 'Gandhi Jayanti',       type: 'both' as const, is_odisha: false },
  { id: 'h12', date: '2026-10-02', name_or: 'ଦୁର୍ଗା ପୂଜା',               name_en: 'Durga Puja',           type: 'both' as const, is_odisha: false },
  { id: 'h23', date: '2026-10-17', name_or: 'କୁମାର ପୂର୍ଣ୍ଣିମା',          name_en: 'Kumar Purnima',        type: 'govt' as const, is_odisha: true },
  { id: 'h13', date: '2026-10-20', name_or: 'ଦୀପାବଳୀ',                  name_en: 'Diwali',               type: 'both' as const, is_odisha: false },
  { id: 'h14', date: '2026-11-05', name_or: 'ଗୁରୁ ନାନକ ଜୟନ୍ତୀ',          name_en: 'Guru Nanak Jayanti',   type: 'both' as const, is_odisha: false },
  { id: 'h24', date: '2026-11-14', name_or: 'ଶ୍ରୀ ଜଗନ୍ନାଥ ଜୟନ୍ତୀ',      name_en: 'Jagannath Jayanti',    type: 'govt' as const, is_odisha: true },
  { id: 'h15', date: '2026-12-25', name_or: 'ଖ୍ରୀଷ୍ଟ ଜନ୍ମ ଦିବସ',         name_en: 'Christmas Day',        type: 'both' as const, is_odisha: false },
];
