/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/openmeteo`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useDynamicFont`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/panjikaService`; params?: Router.UnknownInputParams; } | { pathname: `/../store/usePanjikaStore`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/holidays` | `/holidays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownInputParams; } | { pathname: `/messages/compose`; params?: Router.UnknownInputParams; } | { pathname: `/festival/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/messages/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/openmeteo`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useDynamicFont`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/panjikaService`; params?: Router.UnknownOutputParams; } | { pathname: `/../store/usePanjikaStore`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/holidays` | `/holidays`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownOutputParams; } | { pathname: `/messages/compose`; params?: Router.UnknownOutputParams; } | { pathname: `/festival/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/messages/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/../lib/openmeteo${`?${string}` | `#${string}` | ''}` | `/../hooks/useDynamicFont${`?${string}` | `#${string}` | ''}` | `/../lib/panjikaService${`?${string}` | `#${string}` | ''}` | `/../store/usePanjikaStore${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/holidays${`?${string}` | `#${string}` | ''}` | `/holidays${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/messages${`?${string}` | `#${string}` | ''}` | `/messages${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/weather${`?${string}` | `#${string}` | ''}` | `/weather${`?${string}` | `#${string}` | ''}` | `/messages/compose${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/openmeteo`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useDynamicFont`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/panjikaService`; params?: Router.UnknownInputParams; } | { pathname: `/../store/usePanjikaStore`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/holidays` | `/holidays`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/messages` | `/messages`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/weather` | `/weather`; params?: Router.UnknownInputParams; } | { pathname: `/messages/compose`; params?: Router.UnknownInputParams; } | `/festival/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/messages/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/festival/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/messages/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
